# -*- coding: utf-8 -*-
"""mylib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eYm7eOyZknYKWxWXOD4WsysWucJYGX57
"""

def MyFunction():
  print ('My imported function')

